version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db_sd:
    container_name: 'db_sd'
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - ./mysql_dev:/var/lib/mysql
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql 
    env_file:
      - ./mysql.env
    networks:
      - app-tier