# Request IDs
CREATE_MOVIE_REQUEST_ID = 1
FIND_MOVIE_BY_ID_REQUEST_ID = 2
UPDATE_MOVIE_REQUEST_ID = 3
DELETE_MOVIE_REQUEST_ID = 4
FIND_MOVIE_BY_ACTOR_REQUEST_ID = 5
FIND_MOVIE_BY_CATEGORY_REQUEST_ID = 6

HOST = '127.0.0.1'
PORT = 6666